import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { toast } from '@/hooks/useToast'

// ═══════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════

export type MemoPriority = 'routine' | 'normal' | 'important' | 'critical'

export interface OfficialMemo {
  id: string
  memo_number: string
  title: string
  body: string
  priority: MemoPriority
  issued_by: string
  issuer_name: string
  issuer_role: string
  target_roles: string[]
  requires_acknowledgment: boolean
  valid_until: string | null
  attachments: any[]
  is_active: boolean
  created_at: string
  updated_at: string
  // Computed fields (from RPC)
  is_acknowledged?: boolean
  acknowledged_at?: string | null
  is_expired?: boolean
}

export interface MemoWithStats extends OfficialMemo {
  total_recipients?: number
  acknowledged_count?: number
  pending_count?: number
  acknowledgment_rate?: number
}

// ═══════════════════════════════════════════════════════════
// Hooks
// ═══════════════════════════════════════════════════════════

/**
 * Fetch all memos (admin view — all memos, not filtered by target)
 */
export function useMemos(enabled = true) {
  return useQuery({
    queryKey: ['memos'],
    queryFn: async (): Promise<OfficialMemo[]> => {
      const { data, error } = await supabase
        .from('official_memos')
        .select('*')
        .eq('is_active', true)
        .order('created_at', { ascending: false })
      if (error) throw error
      return data || []
    },
    enabled,
  })
}

/**
 * Fetch memos for the current user (with acknowledgment status)
 */
export function useUserMemos(enabled = true) {
  return useQuery({
    queryKey: ['user-memos'],
    queryFn: async (): Promise<OfficialMemo[]> => {
      const { data, error } = await supabase.rpc('get_user_memos')
      if (error) throw error
      return data || []
    },
    enabled,
  })
}

/**
 * Fetch acknowledgment stats for a memo (admin only)
 */
export function useMemoAckStats(memoId: string | null) {
  return useQuery({
    queryKey: ['memo-ack-stats', memoId],
    queryFn: async () => {
      if (!memoId) return null
      const { data, error } = await supabase.rpc('get_memo_acknowledgment_stats', {
        p_memo_id: memoId,
      })
      if (error) throw error
      return data?.[0] || {
        total_recipients: 0,
        acknowledged_count: 0,
        pending_count: 0,
        acknowledgment_rate: 0,
      }
    },
    enabled: !!memoId,
  })
}

/**
 * Create a new memo (admin/central/governorate only)
 */
export function useCreateMemo() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: async (input: {
      title: string
      body: string
      priority: MemoPriority
      target_roles: string[]
      requires_acknowledgment: boolean
      valid_until?: string | null
    }): Promise<string | null> => {
      const { data: userData } = await supabase.auth.getUser()
      if (!userData.user) throw new Error('Not authenticated')

      const { data: profile } = await supabase
        .from('profiles')
        .select('role, full_name')
        .eq('id', userData.user.id)
        .single()

      const { data, error } = await supabase
        .from('official_memos')
        .insert({
          memo_number: '', // auto-generated by trigger
          title: input.title,
          body: input.body,
          priority: input.priority,
          issued_by: userData.user.id,
          issuer_role: profile?.role || 'admin',
          issuer_name: profile?.full_name || 'غير معروف',
          target_roles: input.target_roles,
          requires_acknowledgment: input.requires_acknowledgment,
          valid_until: input.valid_until,
          is_active: true,
        })
        .select('id')
        .single()

      if (error) throw error
      return data?.id || null
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['memos'] })
      queryClient.invalidateQueries({ queryKey: ['user-memos'] })
      toast.success('تم إصدار التعميم بنجاح')
    },
    onError: (error: any) => {
      toast.error(`فشل: ${error.message}`)
    },
  })
}

/**
 * Acknowledge a memo (mark as read by current user)
 */
export function useAcknowledgeMemo() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: async (memoId: string): Promise<void> => {
      const { data: userData } = await supabase.auth.getUser()
      if (!userData.user) throw new Error('Not authenticated')

      const { error } = await supabase
        .from('memo_acknowledgments')
        .upsert(
          {
            memo_id: memoId,
            user_id: userData.user.id,
            acknowledged_at: new Date().toISOString(),
          },
          { onConflict: 'memo_id, user_id' }
        )
      if (error) throw error
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['user-memos'] })
      queryClient.invalidateQueries({ queryKey: ['memos'] })
      toast.success('تم إقرار استلام التعميم')
    },
    onError: (error: any) => {
      toast.error(`فشل: ${error.message}`)
    },
  })
}

/**
 * Deactivate (soft delete) a memo — admin only
 */
export function useDeactivateMemo() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: async (memoId: string): Promise<void> => {
      const { error } = await supabase
        .from('official_memos')
        .update({ is_active: false })
        .eq('id', memoId)
      if (error) throw error
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['memos'] })
      queryClient.invalidateQueries({ queryKey: ['user-memos'] })
      toast.success('تم حذف التعميم')
    },
    onError: (error: any) => {
      toast.error(`فشل: ${error.message}`)
    },
  })
}
