-- PLACEHOLDER: This migration was renamed to 068_reduce_postgrest_max_rows.sql
-- This file exists only to satisfy supabase db push migration history check.
-- The actual SQL was already applied to the production database.
